# EC2 내에 설치되어 있는 Code Deploy Agent 가 아래의 내용을 읽어서 작업 수행.

version: 0.0
os: linux

files:
  # S3에 저장한 파일들 중 destination(AWS EC2)으로 이동시킬 대상을 지정한다.
  # / 이라고 지정하면 S3에 저장한 전체 파일을 뜻한다.
  - source: /
    # EC2의 어떤 경로에 저장할 지 지정한다.
    destination: /home/ubuntu/concert-booking-server

# code deploy가 어떤 권한을 가지고 수행할건지
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart: # code deploy 실행할때 어떤 작업을 할건지 기재
    - location: scripts/codedeploy/start-server.sh # shell script 파일 실행
      timeout: 60 # 60초 까지만
      runas: ubuntu # ubuntu user로 실행.