spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hhp
    password: hhp
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug


server:
  servlet:
    context-path: /
  port: 8080