name: dev Github Actions CI / Docker Hub CD

on:
  push:
    branches:
      - develop
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Github Repository에 올린 파일들을 불러오기
      uses: actions/checkout@v4

    - name: JDK 17버전 설치
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: application.yml 파일 만들기
      run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-dev.yml

    - name: gradlew 실행 권한추가, 테스트 및 빌드하기
      run: |
        chmod +x ./gradlew
        ./gradlew clean build

    - name: 빌드된 파일 확인
      run: |
        ls
        pwd

    ### DOCKERHUB 업로드
    - name: Checkout Repository
      uses: actions/checkout@v2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  
        password: ${{ secrets.DOCKERHUB_TOKEN }}     

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/concert-booking:${{ github.sha }}
